apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Jaeger
    orgId: 1
  - name: Alertmanager
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      prometheusType: Prometheus
      prometheusVersion: 3.12.0

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{log_scope="application"} | json | trace_id="$${__trace.traceId}"'

  - name: Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
